platform :ios, '10.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'PDFExample' do

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])


  target 'PDFExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PDFExample-tvOS' do
  # Pods for PDFExample-tvOS

  target 'PDFExample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
